server:
  port: 8888
# 应用名称
spring:
  application:
    name: funicorn-authorization-server

  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/funicorn_upms?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: Liuhao2023@


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: true

funicorn:
  logger:
    enable: true
    app-name: funicorn-authorization-server
    keep-alive-time-minutes: 5
    server-addr: 139.9.72.138:17777
    client:
      port: 8888
      client-secret: bd4f807b2f86466699119ca97464f266